# -*- coding: utf-8 -*-
"""ApacheSpark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yAS262PO_rmwpBCEuMG0O2OiqeJ2SIl5
"""

pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('Missing').getOrCreate()

training = spark.read.csv('data.csv',header = True , inferSchema=True)

training.show()

training.columns

from pyspark.ml.feature import VectorAssembler

feature = VectorAssembler(inputCols=["Age","Experience"],outputCol="Independent feature")

output = feature.transform(training)

output.show()

finaldata = output.select("Independent feature","Salary")

finaldata.show()

from pyspark.ml.regression import LinearRegression

train_data,test_data = finaldata.randomSplit([0.65,0.35])

reg = LinearRegression(featuresCol = 'Independent feature',labelCol = 'Salary')

reg = reg.fit(train_data)

reg.coefficients

reg.intercept

Pred_result = reg.evaluate(test_data)

Pred_result.predictions.show()

Pred_result.meanAbsoluteError,Pred_result.meanSquaredError